// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/snippet.proto

package snippetpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snippet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	LanguageHint  string                 `protobuf:"bytes,5,opt,name=language_hint,json=languageHint,proto3" json:"language_hint,omitempty"`
	Visibility    string                 `protobuf:"bytes,6,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snippet) Reset() {
	*x = Snippet{}
	mi := &file_v1_snippet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snippet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snippet) ProtoMessage() {}

func (x *Snippet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snippet.ProtoReflect.Descriptor instead.
func (*Snippet) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{0}
}

func (x *Snippet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Snippet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Snippet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Snippet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Snippet) GetLanguageHint() string {
	if x != nil {
		return x.LanguageHint
	}
	return ""
}

func (x *Snippet) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Snippet) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Snippet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Snippet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNumber    int32                  `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_v1_snippet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalItems    int32                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_v1_snippet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PaginationResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PaginationResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type CreateSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LanguageHint  *string                `protobuf:"bytes,3,opt,name=language_hint,json=languageHint,proto3,oneof" json:"language_hint,omitempty"`
	Visibility    *string                `protobuf:"bytes,4,opt,name=visibility,proto3,oneof" json:"visibility,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnippetRequest) Reset() {
	*x = CreateSnippetRequest{}
	mi := &file_v1_snippet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnippetRequest) ProtoMessage() {}

func (x *CreateSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnippetRequest.ProtoReflect.Descriptor instead.
func (*CreateSnippetRequest) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSnippetRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSnippetRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateSnippetRequest) GetLanguageHint() string {
	if x != nil && x.LanguageHint != nil {
		return *x.LanguageHint
	}
	return ""
}

func (x *CreateSnippetRequest) GetVisibility() string {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return ""
}

func (x *CreateSnippetRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateSnippetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnippetResponse) Reset() {
	*x = CreateSnippetResponse{}
	mi := &file_v1_snippet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnippetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnippetResponse) ProtoMessage() {}

func (x *CreateSnippetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnippetResponse.ProtoReflect.Descriptor instead.
func (*CreateSnippetResponse) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSnippetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnippetRequest) Reset() {
	*x = GetSnippetRequest{}
	mi := &file_v1_snippet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnippetRequest) ProtoMessage() {}

func (x *GetSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnippetRequest.ProtoReflect.Descriptor instead.
func (*GetSnippetRequest) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{5}
}

func (x *GetSnippetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSnippetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snippet       *Snippet               `protobuf:"bytes,1,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnippetResponse) Reset() {
	*x = GetSnippetResponse{}
	mi := &file_v1_snippet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnippetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnippetResponse) ProtoMessage() {}

func (x *GetSnippetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnippetResponse.ProtoReflect.Descriptor instead.
func (*GetSnippetResponse) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{6}
}

func (x *GetSnippetResponse) GetSnippet() *Snippet {
	if x != nil {
		return x.Snippet
	}
	return nil
}

type ListMySnippetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMySnippetsRequest) Reset() {
	*x = ListMySnippetsRequest{}
	mi := &file_v1_snippet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMySnippetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMySnippetsRequest) ProtoMessage() {}

func (x *ListMySnippetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMySnippetsRequest.ProtoReflect.Descriptor instead.
func (*ListMySnippetsRequest) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{7}
}

func (x *ListMySnippetsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListMySnippetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snippets      []*Snippet             `protobuf:"bytes,1,rep,name=snippets,proto3" json:"snippets,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMySnippetsResponse) Reset() {
	*x = ListMySnippetsResponse{}
	mi := &file_v1_snippet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMySnippetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMySnippetsResponse) ProtoMessage() {}

func (x *ListMySnippetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMySnippetsResponse.ProtoReflect.Descriptor instead.
func (*ListMySnippetsResponse) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{8}
}

func (x *ListMySnippetsResponse) GetSnippets() []*Snippet {
	if x != nil {
		return x.Snippets
	}
	return nil
}

func (x *ListMySnippetsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPublicSnippetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	OwnerId       *string                `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3,oneof" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicSnippetsRequest) Reset() {
	*x = ListPublicSnippetsRequest{}
	mi := &file_v1_snippet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicSnippetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicSnippetsRequest) ProtoMessage() {}

func (x *ListPublicSnippetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicSnippetsRequest.ProtoReflect.Descriptor instead.
func (*ListPublicSnippetsRequest) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{9}
}

func (x *ListPublicSnippetsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPublicSnippetsRequest) GetOwnerId() string {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return ""
}

type ListPublicSnippetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snippets      []*Snippet             `protobuf:"bytes,1,rep,name=snippets,proto3" json:"snippets,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicSnippetsResponse) Reset() {
	*x = ListPublicSnippetsResponse{}
	mi := &file_v1_snippet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicSnippetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicSnippetsResponse) ProtoMessage() {}

func (x *ListPublicSnippetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicSnippetsResponse.ProtoReflect.Descriptor instead.
func (*ListPublicSnippetsResponse) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{10}
}

func (x *ListPublicSnippetsResponse) GetSnippets() []*Snippet {
	if x != nil {
		return x.Snippets
	}
	return nil
}

func (x *ListPublicSnippetsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	LanguageHint  *string                `protobuf:"bytes,4,opt,name=language_hint,json=languageHint,proto3,oneof" json:"language_hint,omitempty"`
	Visibility    *string                `protobuf:"bytes,5,opt,name=visibility,proto3,oneof" json:"visibility,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSnippetRequest) Reset() {
	*x = UpdateSnippetRequest{}
	mi := &file_v1_snippet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSnippetRequest) ProtoMessage() {}

func (x *UpdateSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSnippetRequest.ProtoReflect.Descriptor instead.
func (*UpdateSnippetRequest) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSnippetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSnippetRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateSnippetRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdateSnippetRequest) GetLanguageHint() string {
	if x != nil && x.LanguageHint != nil {
		return *x.LanguageHint
	}
	return ""
}

func (x *UpdateSnippetRequest) GetVisibility() string {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return ""
}

func (x *UpdateSnippetRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateSnippetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snippet       *Snippet               `protobuf:"bytes,1,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSnippetResponse) Reset() {
	*x = UpdateSnippetResponse{}
	mi := &file_v1_snippet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSnippetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSnippetResponse) ProtoMessage() {}

func (x *UpdateSnippetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSnippetResponse.ProtoReflect.Descriptor instead.
func (*UpdateSnippetResponse) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSnippetResponse) GetSnippet() *Snippet {
	if x != nil {
		return x.Snippet
	}
	return nil
}

type DeleteSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnippetRequest) Reset() {
	*x = DeleteSnippetRequest{}
	mi := &file_v1_snippet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnippetRequest) ProtoMessage() {}

func (x *DeleteSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_snippet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnippetRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnippetRequest) Descriptor() ([]byte, []int) {
	return file_v1_snippet_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSnippetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_v1_snippet_proto protoreflect.FileDescriptor

const file_v1_snippet_proto_rawDesc = "" +
	"\n" +
	"\x10v1/snippet.proto\x12\n" +
	"snippet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"\xb1\x02\n" +
	"\aSnippet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12#\n" +
	"\rlanguage_hint\x18\x05 \x01(\tR\flanguageHint\x12\x1e\n" +
	"\n" +
	"visibility\x18\x06 \x01(\tR\n" +
	"visibility\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Q\n" +
	"\x11PaginationRequest\x12\x1f\n" +
	"\vpage_number\x18\x01 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x96\x01\n" +
	"\x12PaginationResponse\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x05R\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xca\x01\n" +
	"\x14CreateSnippetRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12(\n" +
	"\rlanguage_hint\x18\x03 \x01(\tH\x00R\flanguageHint\x88\x01\x01\x12#\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tH\x01R\n" +
	"visibility\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tagsB\x10\n" +
	"\x0e_language_hintB\r\n" +
	"\v_visibility\"'\n" +
	"\x15CreateSnippetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11GetSnippetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12GetSnippetResponse\x12-\n" +
	"\asnippet\x18\x01 \x01(\v2\x13.snippet.v1.SnippetR\asnippet\"V\n" +
	"\x15ListMySnippetsRequest\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.snippet.v1.PaginationRequestR\n" +
	"pagination\"\x89\x01\n" +
	"\x16ListMySnippetsResponse\x12/\n" +
	"\bsnippets\x18\x01 \x03(\v2\x13.snippet.v1.SnippetR\bsnippets\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.snippet.v1.PaginationResponseR\n" +
	"pagination\"\x87\x01\n" +
	"\x19ListPublicSnippetsRequest\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.snippet.v1.PaginationRequestR\n" +
	"pagination\x12\x1e\n" +
	"\bowner_id\x18\x02 \x01(\tH\x00R\aownerId\x88\x01\x01B\v\n" +
	"\t_owner_id\"\x8d\x01\n" +
	"\x1aListPublicSnippetsResponse\x12/\n" +
	"\bsnippets\x18\x01 \x03(\v2\x13.snippet.v1.SnippetR\bsnippets\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.snippet.v1.PaginationResponseR\n" +
	"pagination\"\xfa\x01\n" +
	"\x14UpdateSnippetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x01R\acontent\x88\x01\x01\x12(\n" +
	"\rlanguage_hint\x18\x04 \x01(\tH\x02R\flanguageHint\x88\x01\x01\x12#\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tH\x03R\n" +
	"visibility\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tagsB\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_contentB\x10\n" +
	"\x0e_language_hintB\r\n" +
	"\v_visibility\"F\n" +
	"\x15UpdateSnippetResponse\x12-\n" +
	"\asnippet\x18\x01 \x01(\v2\x13.snippet.v1.SnippetR\asnippet\"&\n" +
	"\x14DeleteSnippetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xc6\x05\n" +
	"\x0eSnippetService\x12q\n" +
	"\rCreateSnippet\x12 .snippet.v1.CreateSnippetRequest\x1a!.snippet.v1.CreateSnippetResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/snippets\x12j\n" +
	"\n" +
	"GetSnippet\x12\x1d.snippet.v1.GetSnippetRequest\x1a\x1e.snippet.v1.GetSnippetResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/snippets/{id}\x12t\n" +
	"\x0eListMySnippets\x12!.snippet.v1.ListMySnippetsRequest\x1a\".snippet.v1.ListMySnippetsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/me/snippets\x12}\n" +
	"\x12ListPublicSnippets\x12%.snippet.v1.ListPublicSnippetsRequest\x1a&.snippet.v1.ListPublicSnippetsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/snippets\x12v\n" +
	"\rUpdateSnippet\x12 .snippet.v1.UpdateSnippetRequest\x1a!.snippet.v1.UpdateSnippetResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/api/v1/snippets/{id}\x12h\n" +
	"\rDeleteSnippet\x12 .snippet.v1.DeleteSnippetRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/snippets/{id}B\"Z nota.snippet/pkg/pb/v1;snippetpbb\x06proto3"

var (
	file_v1_snippet_proto_rawDescOnce sync.Once
	file_v1_snippet_proto_rawDescData []byte
)

func file_v1_snippet_proto_rawDescGZIP() []byte {
	file_v1_snippet_proto_rawDescOnce.Do(func() {
		file_v1_snippet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_snippet_proto_rawDesc), len(file_v1_snippet_proto_rawDesc)))
	})
	return file_v1_snippet_proto_rawDescData
}

var file_v1_snippet_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_v1_snippet_proto_goTypes = []any{
	(*Snippet)(nil),                    // 0: snippet.v1.Snippet
	(*PaginationRequest)(nil),          // 1: snippet.v1.PaginationRequest
	(*PaginationResponse)(nil),         // 2: snippet.v1.PaginationResponse
	(*CreateSnippetRequest)(nil),       // 3: snippet.v1.CreateSnippetRequest
	(*CreateSnippetResponse)(nil),      // 4: snippet.v1.CreateSnippetResponse
	(*GetSnippetRequest)(nil),          // 5: snippet.v1.GetSnippetRequest
	(*GetSnippetResponse)(nil),         // 6: snippet.v1.GetSnippetResponse
	(*ListMySnippetsRequest)(nil),      // 7: snippet.v1.ListMySnippetsRequest
	(*ListMySnippetsResponse)(nil),     // 8: snippet.v1.ListMySnippetsResponse
	(*ListPublicSnippetsRequest)(nil),  // 9: snippet.v1.ListPublicSnippetsRequest
	(*ListPublicSnippetsResponse)(nil), // 10: snippet.v1.ListPublicSnippetsResponse
	(*UpdateSnippetRequest)(nil),       // 11: snippet.v1.UpdateSnippetRequest
	(*UpdateSnippetResponse)(nil),      // 12: snippet.v1.UpdateSnippetResponse
	(*DeleteSnippetRequest)(nil),       // 13: snippet.v1.DeleteSnippetRequest
	(*timestamppb.Timestamp)(nil),      // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 15: google.protobuf.Empty
}
var file_v1_snippet_proto_depIdxs = []int32{
	14, // 0: snippet.v1.Snippet.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: snippet.v1.Snippet.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: snippet.v1.GetSnippetResponse.snippet:type_name -> snippet.v1.Snippet
	1,  // 3: snippet.v1.ListMySnippetsRequest.pagination:type_name -> snippet.v1.PaginationRequest
	0,  // 4: snippet.v1.ListMySnippetsResponse.snippets:type_name -> snippet.v1.Snippet
	2,  // 5: snippet.v1.ListMySnippetsResponse.pagination:type_name -> snippet.v1.PaginationResponse
	1,  // 6: snippet.v1.ListPublicSnippetsRequest.pagination:type_name -> snippet.v1.PaginationRequest
	0,  // 7: snippet.v1.ListPublicSnippetsResponse.snippets:type_name -> snippet.v1.Snippet
	2,  // 8: snippet.v1.ListPublicSnippetsResponse.pagination:type_name -> snippet.v1.PaginationResponse
	0,  // 9: snippet.v1.UpdateSnippetResponse.snippet:type_name -> snippet.v1.Snippet
	3,  // 10: snippet.v1.SnippetService.CreateSnippet:input_type -> snippet.v1.CreateSnippetRequest
	5,  // 11: snippet.v1.SnippetService.GetSnippet:input_type -> snippet.v1.GetSnippetRequest
	7,  // 12: snippet.v1.SnippetService.ListMySnippets:input_type -> snippet.v1.ListMySnippetsRequest
	9,  // 13: snippet.v1.SnippetService.ListPublicSnippets:input_type -> snippet.v1.ListPublicSnippetsRequest
	11, // 14: snippet.v1.SnippetService.UpdateSnippet:input_type -> snippet.v1.UpdateSnippetRequest
	13, // 15: snippet.v1.SnippetService.DeleteSnippet:input_type -> snippet.v1.DeleteSnippetRequest
	4,  // 16: snippet.v1.SnippetService.CreateSnippet:output_type -> snippet.v1.CreateSnippetResponse
	6,  // 17: snippet.v1.SnippetService.GetSnippet:output_type -> snippet.v1.GetSnippetResponse
	8,  // 18: snippet.v1.SnippetService.ListMySnippets:output_type -> snippet.v1.ListMySnippetsResponse
	10, // 19: snippet.v1.SnippetService.ListPublicSnippets:output_type -> snippet.v1.ListPublicSnippetsResponse
	12, // 20: snippet.v1.SnippetService.UpdateSnippet:output_type -> snippet.v1.UpdateSnippetResponse
	15, // 21: snippet.v1.SnippetService.DeleteSnippet:output_type -> google.protobuf.Empty
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_snippet_proto_init() }
func file_v1_snippet_proto_init() {
	if File_v1_snippet_proto != nil {
		return
	}
	file_v1_snippet_proto_msgTypes[3].OneofWrappers = []any{}
	file_v1_snippet_proto_msgTypes[9].OneofWrappers = []any{}
	file_v1_snippet_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_snippet_proto_rawDesc), len(file_v1_snippet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_snippet_proto_goTypes,
		DependencyIndexes: file_v1_snippet_proto_depIdxs,
		MessageInfos:      file_v1_snippet_proto_msgTypes,
	}.Build()
	File_v1_snippet_proto = out.File
	file_v1_snippet_proto_goTypes = nil
	file_v1_snippet_proto_depIdxs = nil
}
