jwt:
  expiration: 12h

session:
  expiration: 288h

auth:
  name: "nota.auth"
  env:
    - auth
    - postgres
    - otel
  protected_rpc:
    - "GetUser"
    - "Logout"

gateway:
  name: "nota.gateway"
  env:
    - jwt
    - otel
    - auth
    - gateway
    - snippet
  protected_routes:
    - "/api/v1/auth/logout"
    - "/api/v1/auth/me"
    - "/api/v1/me/snippets"
    - "/api/v1/snippets"

snippet:
  name: "nota.snippet"
  env:
    - snippet
    - postgres
    - otel